"""
Verification script for Asynchronous Run Analysis architecture on IBVAP.
Tests:
1. POST /api/v1/cameras/run-analysis response time (< 1-2 seconds)
2. Immediate return of status: "ANALYZING"
3. Background pipeline progression (YOLO, ByteTrack, Spatial, Behavior, Fusion)
4. Telemetry and MJPEG frame availability
5. Real security event generation and Supabase persistence
6. SHA-256 sealed evidence packaging
7. Concurrency protection (rejection of duplicate / concurrent sessions)
8. Stop analysis lifecycle
9. Memory monitoring
"""
import sys
import time
import json
import os
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from fastapi.testclient import TestClient
from backend.app.main import app
from backend.app.api.routes.cameras import _ANALYSIS_STATUS, _RUNNING_ORCHESTRATORS, _RUNNING_THREADS
from backend.app.api.routes.streams import _LATEST_FRAMES

def main():
    print("=" * 70)
    print("IBVAP ASYNCHRONOUS RUN ANALYSIS VERIFICATION")
    print("=" * 70)

    client = TestClient(app)

    # 1. Clean previous state
    print("\n[STEP 1] Testing Stop Analysis on clean state...")
    stop_resp = client.post("/api/v1/cameras/stop-analysis", json={"camera_id": "DEMO-CAM-01"})
    print(f"  Stop Analysis Response: {stop_resp.status_code}, payload={stop_resp.json()}")

    # 2. Test Run Analysis Response Time
    test_video = "storage/samples/test_video.mp4"
    print(f"\n[STEP 2] Executing POST /api/v1/cameras/run-analysis with '{test_video}'...")
    start_time = time.time()
    run_resp = client.post(
        "/api/v1/cameras/run-analysis",
        json={
            "camera_id": "DEMO-CAM-01",
            "video_file_path": test_video,
            "device": "cpu",
        },
    )
    elapsed_ms = (time.time() - start_time) * 1000.0

    print(f"  Response Status Code: {run_resp.status_code}")
    print(f"  Response Time: {elapsed_ms:.2f} ms")
    assert run_resp.status_code == 200, f"Expected 200, got {run_resp.status_code}: {run_resp.text}"
    assert elapsed_ms < 2000.0, f"Expected response time < 2000 ms, got {elapsed_ms:.2f} ms"

    run_data = run_resp.json()
    print(f"  Returned Session ID: {run_data.get('session_id')}")
    print(f"  Returned Status: {run_data.get('status')}")
    assert run_data.get("status") == "ANALYZING", f"Expected ANALYZING, got {run_data.get('status')}"
    print(f"  SUCCESS: POST /run-analysis returned in {elapsed_ms:.2f} ms with status 'ANALYZING'")

    # 3. Test Concurrency Rejection
    print("\n[STEP 3] Testing Concurrency Protection (Clean Rejection)...")
    dup_resp = client.post(
        "/api/v1/cameras/run-analysis",
        json={
            "camera_id": "DEMO-CAM-01",
            "video_file_path": test_video,
            "device": "cpu",
        },
    )
    print(f"  Duplicate Request Status: {dup_resp.status_code} (Expected 409 Conflict)")
    assert dup_resp.status_code == 409, f"Expected 409 Conflict, got {dup_resp.status_code}: {dup_resp.text}"
    print(f"  Detail: {dup_resp.json().get('detail')}")
    print("  SUCCESS: Concurrent run analysis request cleanly rejected with HTTP 409")

    # 4. Monitor Background Pipeline Execution
    print("\n[STEP 4] Monitoring Background Pipeline Execution...")
    max_wait = 25.0
    poll_start = time.time()
    events_found = []
    first_frame_seen = False

    import psutil
    process = psutil.Process(os.getpid())

    while time.time() - poll_start < max_wait:
        time.sleep(1.0)
        st_resp = client.get("/api/v1/cameras/DEMO-CAM-01/analysis-status")
        st_data = st_resp.json()
        status = st_data.get("status")
        is_running = st_data.get("is_running")
        mem_mb = process.memory_info().rss / (1024 * 1024)

        # Check latest frame buffer
        has_frame = "DEMO-CAM-01" in _LATEST_FRAMES and len(_LATEST_FRAMES["DEMO-CAM-01"]) > 0
        if has_frame and not first_frame_seen:
            first_frame_seen = True
            time_to_first_frame = time.time() - start_time
            print(f"  [FRAME 1] MJPEG buffer primed! Time to first frame: {time_to_first_frame:.2f}s, frame size: {len(_LATEST_FRAMES['DEMO-CAM-01'])} bytes")

        # Check events
        ev_resp = client.get("/api/v1/events?camera_id=DEMO-CAM-01")
        if ev_resp.status_code == 200:
            events_found = ev_resp.json()

        print(f"  T+{(time.time() - poll_start):.1f}s | Status={status} | IsRunning={is_running} | Events={len(events_found)} | RAM={mem_mb:.1f} MB")

        if len(events_found) > 0 and first_frame_seen:
            print(f"  Real events detected by background pipeline! Continuing observation...")
            break

    assert first_frame_seen, "Pipeline did not prime MJPEG frame buffer"
    assert len(events_found) > 0, "No real events generated by background pipeline"

    # 5. Verify Security Event and Evidence Integrity
    print("\n[STEP 5] Verifying Security Event & SHA-256 Evidence Package...")
    ev = events_found[0]
    print(f"  Event ID: {ev['id']}")
    print(f"  Event Type: {ev['event_type']}")
    print(f"  Priority: {ev['priority']}")
    print(f"  Risk Score: {ev['risk_score']}")
    print(f"  Reason Codes: {ev.get('reason_codes')}")

    evid_resp = client.get(f"/api/v1/events/{ev['id']}/evidence")
    print(f"  Evidence Status: {evid_resp.status_code}")
    if evid_resp.status_code == 200:
        evid_data = evid_resp.json()
        print(f"  Evidence Package ID: {evid_data.get('id')}")
        print(f"  SHA-256 Seal: {evid_data.get('sha256_seal')}")
        print(f"  Evidence Records: {len(evid_data.get('evidence_records', []))}")
        for rec in evid_data.get("evidence_records", []):
            print(f"    - [{rec.get('evidence_type')}] file={rec.get('file_path')} sha256={rec.get('sha256')[:16]}... storage_url={rec.get('storage_url')}")

    # 6. Test Acknowledgment
    print("\n[STEP 6] Testing Event Acknowledgment...")
    ack_resp = client.post(f"/api/v1/events/{ev['id']}/acknowledge", json={"acknowledged_by": "SIH-Operator-01"})
    print(f"  Ack Response: {ack_resp.status_code}, status={ack_resp.json().get('status')}")
    assert ack_resp.status_code == 200

    # 7. Test Stop Analysis & Memory Cleanup
    print("\n[STEP 7] Testing Stop Analysis & Resource Cleanup...")
    stop_resp = client.post("/api/v1/cameras/stop-analysis", json={"camera_id": "DEMO-CAM-01"})
    print(f"  Stop Status: {stop_resp.status_code}, {stop_resp.json()}")
    assert stop_resp.status_code == 200

    # Check status endpoint after stop
    st_resp = client.get("/api/v1/cameras/DEMO-CAM-01/analysis-status")
    print(f"  Post-Stop Analysis Status: {st_resp.json()}")
    assert st_resp.json().get("status") == "COMPLETED"
    assert st_resp.json().get("is_running") == False

    final_mem = process.memory_info().rss / (1024 * 1024)
    print(f"  Final Memory: {final_mem:.1f} MB")

    print("\n" + "=" * 70)
    print("ALL ASYNC RUN ANALYSIS ACCEPTANCE CRITERIA SATISFIED!")
    print("=" * 70)

if __name__ == "__main__":
    main()
